### ISSUE TITLE
Review and test text-to-speech

### ISSUE THREAD

**Issue by 900miles** [sensein/senselab#108]
### Description

This issue is to track feedback for the senselab text-to-speech task.

### Tasks

- [x] Review tutorial
- [x] Review documentation
- [x] Review code
- [x] Test edge cases

### Freeform Notes
Fabio's documentation guidelines:
- Documentation - Considering the tasks that you have implemented, work on the documentation
- Explain what the task is about, give an overview of the metrics generally used to evaluate the task, report some existing benchmarks in the literature, if any
- Make docstrings in Google style and consistent with with the CONTRIBUTING.md document

Notebook tutorial

- Prepare a jupyter notebook tutorial for each of your tasks. This should show how to use the senselab interface that you have implemented, both with and without using pydra

**Comment by 900miles** [comment]
## Documentation
There are no tutorials for this task. There is no explanation for what the task is about, what the metrics are for evaluating the tasks, nor any benchmarks in the literature. There are no examples in the docstring of how the function should be used. The doctring says that `model` should be of type `SenselabModel` but the code requires it to be of type `HFModel`.

**Comment by 900miles** [comment]
## Code
When running `synthesize_texts`, I get the following warning:
```
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:10000 for open-end generation.
```

This seems to happen once per text synthesized.

**Comment by 900miles** [comment]
The supported models seems to be incorrect. The documentation is vague, but seems to imply that any huggingface tts model is supported. However, I have tried `microsoft/speecht5_tts`, `microsoft/speecht5_tts`, `fishaudio/fish-speech-1.2-sft`, and `facebook/mms-tts-eng` and all have failed with various errors. `suno/bark` is the only one I have tried so far that works.

**Comment by 900miles** [comment]
## Tests
The tests seem to be missing two cases: 1. testing with different models other than the default and 2. testing the case of synthesizing more than one text at one time.

**Comment by 900miles** [comment]
Otherwise synthesizing speech with the default model seems to be working well! @fabiocat93 I believe this is your module, please take a look at my comments when you get a chance and let me know if you have any questions :)

**Comment by fabiocat93** [comment]
> The supported models seems to be incorrect. The documentation is vague, but seems to imply that any huggingface tts model is supported. However, I have tried `microsoft/speecht5_tts`, `microsoft/speecht5_tts`, `fishaudio/fish-speech-1.2-sft`, and `facebook/mms-tts-eng` and all have failed with various errors. `suno/bark` is the only one I have tried so far that works.

The space of text to speech is pretty messed up. @wilke0818 is currently working on integrating some more tools (e.g., styletts2). i agree we should specify what models we do support (but of course we cannot check all huggingface models ourselves) or at least recommend the "best" models according to us

**Comment by fabiocat93** [comment]
@900miles i have moved the discussion to https://github.com/sensein/senselab/pull/129, to make comments and tracking easier
