### ISSUE TITLE
Review and test speech-to-text task

### ISSUE THREAD

**Issue by 900miles** [sensein/senselab#109]
### Description

This issue is to track feedback for the senselab speech-to-text task.

### Tasks

- [x] Review tutorial
- [x] Review documentation
- [x] Review code
- [x] Test edge cases

**Comment by 900miles** [comment]
## Documentation

There are no tutorials for this task. There is no explanation for what the task is about or any benchmarks in the literature. There is no discussion of the differences between the various metrics or when to choose one over the other. There are no examples in the docstring of how the function should be used. The doctring and function header says that model should be of type SenselabModel, but the code requires it to be of type HFModel. There is no documentation on which models are supported. There is no default model.

**Comment by 900miles** [comment]
## Code

Looks good! 👍

**Comment by 900miles** [comment]
## Tests
Missing case of using different models. Missing case of transcribing more than one audio at once.

**Comment by 900miles** [comment]
@fabiocat93 I believe this was your module as well.

**Comment by fabiocat93** [comment]
hi @900miles , i have done some edits addressing your comments. Let me know what do you think! Thanks!

**Comment by fabiocat93** [comment]
btw, this should also solve [this other issue](https://github.com/sensein/senselab/issues/118).
