### ISSUE TITLE
Add speaker diarization

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#11]

**Comment by ibevers** [comment]
RE Slack conversation: problem where each row has a copy of diarizations for every row appended to it rather than just the diarization for that row

**Comment by ibevers** [comment]
> RE Slack conversation: problem where each row has a copy of diarizations for every row appended to it rather than just the diarization for that row

@Fabio In [this commit](https://github.com/sensein/senselab/commit/9ffe82c6f488b4ea3e20e13a9df8251d1e6bd529), you changed the dataset to custom audio files in `scripts/pyannote_31_experiment.py`. I realize that you are using the code you wrote to convert to a HF dataset. 

However, that is not necessarily equivalent to using a dataset retrieved from HF. Are you sure that your [latest changes](https://github.com/sensein/senselab/commit/285cbff66586c62868c65c96917294f9edab7731) are robust to this case?

Also, do you have any insight into why this error might have been occurring?

**Comment by ibevers** [comment]
I will write test cases for both.

**Comment by fabiocat93** [comment]
hi @ibevers! 

> @fabio In [this commit](https://github.com/sensein/senselab/commit/9ffe82c6f488b4ea3e20e13a9df8251d1e6bd529), you changed the dataset to custom audio files in scripts/pyannote_31_experiment.py. I realize that you are using the code you wrote to convert to a HF dataset.
> 
> However, that is not necessarily equivalent to using a dataset retrieved from HF. Are you sure that your [latest changes](https://github.com/sensein/senselab/commit/285cbff66586c62868c65c96917294f9edab7731) are robust to this case?
> 

I have added one extra example using an HF dataset downloaded from the hub so you can use it as an example. 


> I will write test cases for both.

Thanks. Even before that, can you work on a more general method to using pyannote.audio in all its functions? You can take inspiration from the other existing tasks (e.g., speech to text)

**Comment by ibevers** [comment]
> RE Slack conversation: problem where each row has a copy of diarizations for every row appended to it rather than just the diarization for that row

Thank you @fabiocat93 , however, this doesn't address my concern. Here is an example of what I mean (generated using the code with your changes):

Output using the first two rows of `PolyAI/minds14`:
```
 "path": [
        "/Users/isaacbevers/.cache/huggingface/datasets/downloads/extracted/97d649eeba23e369c4435702af88e14910ce18dcdcd485c95ef562d2cb4d3845/en-US~JOINT_ACCOUNT/602ba55abb1e6d0fbce92065.wav",
        "/Users/isaacbevers/.cache/huggingface/datasets/downloads/extracted/97d649eeba23e369c4435702af88e14910ce18dcdcd485c95ef562d2cb4d3845/en-US~JOINT_ACCOUNT/602baf24bb1e6d0fbce922a7.wav"
    ]

    "pyannote31_diarization": [
        {
            "[ 00:00:00.435 -->  00:00:03.372]": null,
            "[ 00:00:02.005 -->  00:00:05.329]": "SPEAKER_00",
            "[ 00:00:03.878 -->  00:00:05.717]": null,
            "[ 00:00:07.287 -->  00:00:09.683]": "SPEAKER_00"
        },
        {
            "[ 00:00:00.435 -->  00:00:03.372]": "SPEAKER_00",
            "[ 00:00:02.005 -->  00:00:05.329]": null,
            "[ 00:00:03.878 -->  00:00:05.717]": "SPEAKER_00",
            "[ 00:00:07.287 -->  00:00:09.683]": null
        }
    ]
```

Output using the first three lines:
```
    "path": [
        "/Users/isaacbevers/.cache/huggingface/datasets/downloads/extracted/97d649eeba23e369c4435702af88e14910ce18dcdcd485c95ef562d2cb4d3845/en-US~JOINT_ACCOUNT/602ba55abb1e6d0fbce92065.wav",
        "/Users/isaacbevers/.cache/huggingface/datasets/downloads/extracted/97d649eeba23e369c4435702af88e14910ce18dcdcd485c95ef562d2cb4d3845/en-US~JOINT_ACCOUNT/602baf24bb1e6d0fbce922a7.wav",
        "/Users/isaacbevers/.cache/huggingface/datasets/downloads/extracted/97d649eeba23e369c4435702af88e14910ce18dcdcd485c95ef562d2cb4d3845/en-US~JOINT_ACCOUNT/602b9f97963e11ccd901cc32.wav"
    ]
    "pyannote31_diarization": [
        {
            "[ 00:00:00.435 -->  00:00:03.372]": null,
            "[ 00:00:01.110 -->  00:00:13.210]": null,
            "[ 00:00:02.005 -->  00:00:05.329]": "SPEAKER_00",
            "[ 00:00:03.878 -->  00:00:05.717]": null,
            "[ 00:00:07.287 -->  00:00:09.683]": "SPEAKER_00",
            "[ 00:00:14.425 -->  00:00:16.754]": null,
            "[ 00:00:19.184 -->  00:00:22.390]": null
        },
        {
            "[ 00:00:00.435 -->  00:00:03.372]": "SPEAKER_00",
            "[ 00:00:01.110 -->  00:00:13.210]": null,
            "[ 00:00:02.005 -->  00:00:05.329]": null,
            "[ 00:00:03.878 -->  00:00:05.717]": "SPEAKER_00",
            "[ 00:00:07.287 -->  00:00:09.683]": null,
            "[ 00:00:14.425 -->  00:00:16.754]": null,
            "[ 00:00:19.184 -->  00:00:22.390]": null
        },
        {
            "[ 00:00:00.435 -->  00:00:03.372]": null,
            "[ 00:00:01.110 -->  00:00:13.210]": "SPEAKER_00",
            "[ 00:00:02.005 -->  00:00:05.329]": null,
            "[ 00:00:03.878 -->  00:00:05.717]": null,
            "[ 00:00:07.287 -->  00:00:09.683]": null,
            "[ 00:00:14.425 -->  00:00:16.754]": "SPEAKER_00",
            "[ 00:00:19.184 -->  00:00:22.390]": "SPEAKER_00"
        }
    ]
```
Why are the time segments for every row included in the output for each row? Do you know if this a peculiarity of the way that Pyannote processes the data, or does the way map is being used need to be changed somehow?

"I don't know" is a fine answer. I was just wondering if you've seen a similar phenomenon when using map on other HF datasets with other models.

**Comment by fabiocat93** [comment]
if that's the output of the code that I wrote, then the answer is that that is not the output of a specific row, but the output for the entire dataset :)

**Comment by ibevers** [comment]
I'm aware of that, but why does the length of each entry vary depending on the number of input rows? I would expect the number of time segments to be invariant to the number of input rows. In other words, do you know why when we have two input rows, we have:
```
        {
            "[ 00:00:00.435 -->  00:00:03.372]": null,
            "[ 00:00:02.005 -->  00:00:05.329]": "SPEAKER_00",
            "[ 00:00:03.878 -->  00:00:05.717]": null,
            "[ 00:00:07.287 -->  00:00:09.683]": "SPEAKER_00"
        }
```
Whereas when we have three input rows, we have:
```
        {
            "[ 00:00:00.435 -->  00:00:03.372]": null,
            "[ 00:00:01.110 -->  00:00:13.210]": null,
            "[ 00:00:02.005 -->  00:00:05.329]": "SPEAKER_00",
            "[ 00:00:03.878 -->  00:00:05.717]": null,
            "[ 00:00:07.287 -->  00:00:09.683]": "SPEAKER_00",
            "[ 00:00:14.425 -->  00:00:16.754]": null,
            "[ 00:00:19.184 -->  00:00:22.390]": null
        }
```

I know the non-null segments are the same, but it is misleading to have null segments that don't necessarily correspond to the length of the audio clip being processed.

**Comment by fabiocat93** [comment]
oh wow! That's weird, you are right. i will look at it. meanwhile, pls open an issue on pyannote.audio and avoid using mapping for now

**Comment by ibevers** [comment]
@fabiocat93 While fixing a bug with batching with the help of @GasserElbanna, I figured out the cause of this issue and fixed it. There is nothing wrong with pyannote.audio.  

When the dictionary returned by the function used by map has dictionaries as sub-elements, Hugging Face map turns these into sub-columns. Accordingly, by having dictionaries for each diarization, each segment string becomes a sub-column title. Since there are no speaker IDs for segments from audio files that differ from a given audio file, the entries for the the sub-column associated with these other audio files are null.

The solution is to not use dictionary sub-elements in the return data structure for the diarization of an audio file batch, which is fixed in the latest commit.
