### ISSUE TITLE
Review and test voice cloning task

### ISSUE THREAD

**Issue by 900miles** [sensein/senselab#110]
### Description

This issue is to track feedback for the senselab voice cloning task.

### Tasks

- [x]  Review tutorial
- [x]  Review documentation
- [x]  Review code
- [x]  Test edge cases

**Comment by 900miles** [comment]
## Documentation
There are no tutorials for this task. There is no explanation for what the task is about, what the metrics are for evaluating the tasks, nor any benchmarks in the literature. The docstrings do not follow the Google format. There are no examples to follow in the docstrings or anywhere else. The term `KNNVC` is used without ever specifying what it is. `knnvc.py` also does not have Google-conforming docstrings

**Comment by 900miles** [comment]
## Code
The function header specifies `model` as a parameter, but only a single model can be used so there is no choice for the user to make. The function header specifies `**kwargs` as a parameter, but only uses it to get `topk` and `prematched_vocoder`. It would be clearer to specify those arguments directly in the function header with the default parameters already specified (`4` and `True` respectively). 

In `knnvc.py`, this error message can be clearer: `f"Sampling rates {source_sampling_rate} and/or {target_sampling_rate} are not supported.", for example by saying something like: 
```
f"Sampling rates for the source audio ({source_sampling_rate}) and/or the target audio ({target_sampling_rate}) are not supported."
f"Only {supported_sampling_rate} sampling rate is supported."
f"Offending audios: source_audio={source_audio}, target_audio={target_audio}"
```
Perhaps not exactly this, but it should specify which audio file corresponds to which sampling rate so the user can instantly see exactly which audio file is the problem. Same thing with the `only mono audio files are supported` error, this should specify exactly which audio is not mono. Also `Source and target audios must have the same length.` should be replaced with `The list of source and target audios must have the same length.`

**Comment by 900miles** [comment]
## Tests
Tests are very comprehensive but they are missing the case of cloning 2+ audios at the same time, possible with different lengths

**Comment by 900miles** [comment]
@fabiocat93 I believe this was also your module!

**Comment by fabiocat93** [comment]
@900miles, thank you! i will work on your comments as soon as I have some time...
Also, @wilke0818 is trying to integrate alternative tools for voice cloning (e.g., marts-tts, free), but it's still not clear to us what the best way to integrate submodules is. Maybe @satra can give us some guidance
