### ISSUE TITLE
Bug: Not all submodules appear in pdocs

### ISSUE THREAD

**Issue by 900miles** [sensein/senselab#118]
### Description

https://sensein.group/senselab/senselab.html only shows audio, app and cli as available submodules. 

### Steps to Reproduce

Visit https://sensein.group/senselab/senselab.html

### Expected Results

All available submodules should be linked, including text, utils, and video.

### Actual Results

Only audio, app, and cli are shown.

**Comment by fabiocat93** [comment]
this should be solved by this PR: https://github.com/sensein/senselab/pull/119. @900miles let me know if you still see any issue

**Comment by 900miles** [comment]
Looks like that fixed it! Closed by #119
