### ISSUE TITLE
Support: Installation Instructions don't Work

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#221]
### Issue Description

When I delete my poetry environment and follow the installation instructions in:
https://github.com/sensein/senselab/blob/main/CONTRIBUTING.md

I get the following:
<img width="967" alt="Screenshot 2024-12-12 at 12 29 49 PM" src="https://github.com/user-attachments/assets/b64cfb65-6c12-4476-8b3d-4d4b1dc8d4af" />

This may be related to this recently merged PR:
https://github.com/sensein/senselab/pull/217

@fabiocat93 Why was this merged without the checks passing?

### Environment Details

MacOS

### Attempted Solutions

I have tried with Python3.10, 3.11, and 3.12.

### Reproduction Steps

Follow the installation instructions.

**Comment by 900miles** [comment]
I get a similar issue on a brand new conda environment with `python==3.12.8`:
when running `poetry install --with dev,docs`
```
- Installing antlr4-python3-runtime (4.9.3): Failed

  ChefInstallError

  Failed to install setuptools >= 40.8.0.

  Output:
  Updating dependencies
  Resolving dependencies...

  Package operations: 1 install, 0 updates, 0 removals

    - Installing setuptools (75.6.0)

    RuntimeError

    Unable to find installation candidates for setuptools (75.6.0)

    at ~/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
         70│
         71│             links.append(link)
         72│
         73│         if not links:
      →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
         75│
         76│         # Get the best link
         77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
         78│

  Cannot install setuptools.



  Error:


  at ~/.local/share/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:102 in install
       98│             InstalledRepository.load(self._env),
       99│         )
      100│         installer.update(True)
      101│         if installer.run() != 0:
    → 102│             raise ChefInstallError(requirements, io.fetch_output(), io.fetch_error())
      103│
      104│
      105│ class Chef:
      106│     def __init__(

Cannot install build-system.requires for antlr4-python3-runtime.
 ```

Although it turns out running `poetry install --with dev,docs` again, after that error, installs correctly.

**Comment by ibevers** [comment]
Had vesitigial x86-64 Python versions, which was the source of my difficulties here.
