### ISSUE TITLE
Task: Audio-to-audio voice cloning

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#27]
### Description

Cloning someone's speech into someone's else voice

### Tasks

- [ ] Integrating some pre-trained voice cloning tools (e.g., FreeVC, KNNVC)

**Comment by wilke0818** [comment]
Seems like KNNVC has been implemented? Satra previously mentioned StyleTTS 2.0: https://github.com/yl4579/StyleTTS2
I've previously used StyleTTS1.0 for this task with mixed results but their notebooks are a great example/resource

**Comment by fabiocat93** [comment]
> Seems like KNNVC has been implemented? Satra previously mentioned StyleTTS 2.0: https://github.com/yl4579/StyleTTS2 I've previously used StyleTTS1.0 for this task with mixed results but their notebooks are a great example/resource

we want all good audio-to-audio voice cloning tools here. I have added KNNVC, but we want more, including StyleTTS 2.0. This way, we can enable all types of comparative analyses
