### ISSUE TITLE
Task: Remove 'tasks' from import statements

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#39]
It doesn't seem informative, and it looks cleaner without it:

Example:
from senselab.audio.preprocessing import resample_hf_dataset

is clearer than:

from senselab.audio.tasks.preprocessing import resample_hf_dataset

@fabiocat93 is there a reason to keep it in the import statements?

**Comment by fabiocat93** [comment]
@ibevers, thanks for raising this point!

We may want to have `tasks` and `workflows`/`pipelines` (which are combinations of tasks). For example, the `whisperx` pipeline may combine `automatic speech recognition`, `force alignment`, and `speaker diarization`. Rn, we don't have any pipeline/workflow, but we will pretty soon

**Comment by ibevers** [comment]
Ah, right, I remember we talked about this now. Thanks!
