### ISSUE TITLE
Task: Dimensionality reduction

### ISSUE THREAD

**Issue by fabiocat93** [sensein/senselab#44]
### Description

Implementing an interface for dimensionality reduction

### Tasks

- [x] PCA
- [x] tSNA
- [x] UMAP

**Comment by fabiocat93** [comment]
hi, @900miles ! just a kind reminder: dimensionality reduction is supposed to be included in the release 0.5.0 (this Friday)

**Comment by 900miles** [comment]
Closed by #81
