### ISSUE TITLE
Update interface to remove redundant lines in imports and .api calls

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#95]
I propose updating the interface so that things like:
`from senselab.audio.tasks.preprocessing.preprocessing import resample_audios` and
`from senselab.audio.tasks.speech_to_text.api import transcribe_audios`
become:
`from senselab.audio.tasks.preprocessing import resample_audios`
`from senselab.audio.tasks.speech_to_text import transcribe_audios`
(respectively)

We can do this by editing __init__.py files.

**Comment by fabiocat93** [comment]
great idea. please do it. i think this is going to affect the way `pdoc` will structure and generate the documentation. please, make sure that all pages are still going to be included after this change
